### ISSUE TITLE
DL3009 doesn't make sense with multistage builds

### ISSUE THREAD

**Issue by Monnoroch** [hadolint/hadolint#167]
Also true for some other lints. Perhaps they should only be enforced on the last stage of the build.

**Comment by zemanlx** [comment]
That is true if you plan to build only the last image as an artifact. Unfortunately, that is not always true like in case of  [test.Dockerfile](https://github.com/moby/buildkit/blob/master/hack/dockerfiles/test.Dockerfile) used in https://github.com/moby/buildkit that have all image definitions in one Dockerfile and you pick which one to build with `--target`. 

If you want to save some time in build and do not remove _apt cache_ I believe that feature planned in #165 can be handy. 

I know that your scenario (I believe same as our `Dockerfile`) is more common, but the other scenario (_buildkit_ type) is not possible to catch in case we disable DL3009 for a multistage build because it is part of independent build mechanism.

**Comment by Monnoroch** [comment]
What you said totally makes sense. However with a long Dockerfile I might have to put too many of these disable lines. This doesn't really scale all that well. Perhaps something else can be designed in addition to disabling individual lines?

**Comment by zemanlx** [comment]
Do you have anything specific (an exception mechanism) in your mind?

**Comment by lorenzo** [comment]
@Monnoroch Can you share the case where you think it does not make sense?

**Comment by Monnoroch** [comment]
The case was already discussed above: I install some packages, build software, and then create a second stage that only copies binaries. The linter tells me I need to clean up after installing packages, but I don't: the second stage will not contain them anyway. So adding these cleanups will only make the code bigger, more complicated and less supportable.

**Comment by lorenzo** [comment]
I guess we could detect whether or not an intermediate image is used as the FROM clause downstream. If it is not used, then there is no point in having the warning
