### ISSUE TITLE
DL3022 - COPY --from= when references an external image

### ISSUE THREAD

**Issue by WTFKr0** [hadolint/hadolint#197]
Hi,
Just fall into this

### Expected behavior
`COPY    --from=myregistry/my/image:tag /binary /`
should be correct

### Actual behavior
Prompt a DL3022 error
`COPY --from should reference a previously defined FROM alias`

### Output of `hadolint --version`
```bash
Haskell Dockerfile Linter v1.6.5-0-g933c2e2
```

**Comment by lorenzo** [comment]
Since hadolint cannot perform network requests, I don't think this is a case we are interested in supporting. You may add an exception for that line of code, or entirely disabling the rule using a configuration file.

An alternative would be to trust whatever image name is placed there in the form of `registry/image:tag`, but that would leave common things out like `ubuntu:16`, which has no registry. 

In general, I think it is not good practice to  directly reference external images, but that is only my personal experience.

**Comment by WTFKr0** [comment]
> In general, I think it is not good practice to directly reference external images, but that is only my personal experience.

This is the same as doing : 
```
FROM myimage:tag as dep
COPY --from=dep /binary /
```
This syntax is correct in Hadolint, but take two lines instead of one
:smile:

**Comment by lorenzo** [comment]
I know, but this is the only way I can think of to validate aliases without incurring un network lookups and all the problems they carry.
 
I also think that second form is easier to understand.

**Comment by zemanlx** [comment]
@WTFKr0 Out of interest what is your use case? Why do you need to copy a file from an image that is not temporary/builder?

**Comment by WTFKr0** [comment]
@zemanlx Sure see https://github.com/wtfcoderz/static-healthcheck

**Comment by zemanlx** [comment]
So it is a replacement for `curl`/`wget`. Nice hack :+1:

**Comment by Wirone** [comment]
@lorenzo Common use case for PHP-based images is to do `COPY --from=composer:2 /usr/bin/composer /usr/bin/composer` and include ready-to-use Composer binary. Also for complex build processes sometimes part of them is extracted to some base build images (especially when they don't change often) and then copied into final image, which is more dynamic.

I just wanted to make some improvements using Hadolint but I found 3 occurrences of DL3022 as false-positives.

**Comment by lorenzo** [comment]
@Wirone there is no good way to improve this, other than removing the rule. 

What I do is to include the layer as a FROM and just copy from it. It has the same effect, it’s easy to read, and also makes it possible for hadolint to validate.

**Comment by Wirone** [comment]
@lorenzo I know, I've read comments above 😉 But IMHO it does not make sense - Hadolint encourages to merge consecutive `RUN`s into one to make less layers and on the other hand enforces 2 layers instead of 1 just because it requires copying from _targets_ while `COPY` can work with _images_ too. For me, DL3022 should be removed completely because it validates something that is against documentation.

**Comment by SteppingHat** [comment]
@Wirone +1 with this statement.
Since this contradicts other rules and overall encouragement to merge multiple `RUN` instructions into one, I too think DL3022 should be removed.
I also know of a few docker newbies who are blindly following this rule to split it out, not exactly knowing what they are doing. It hurts to watch 😩

**Comment by rittneje** [comment]
@Wirone @SteppingHat This does not contradict the rule about merging `RUN` instructions. The number of layers in the resulting image is still the same, because either way there is just the one `COPY`.

**Comment by Wirone** [comment]
> This does not contradict the rule about merging `RUN` instructions. The number of layers in the resulting image is still the same, because either way there is just the one `COPY`.

@rittneje It's not a matter of `COPY`s, it's a matter of layers / intermediate containers and readability of `Dockerfile`. Instead of 1 layer `COPY --from` you need to use 2 instructions AND you can't keep them together. This does not work:

```
FROM scratch

FROM composer:2 as dep 
COPY --from=dep /usr/bin/composer ./composer
```

because of `failed to solve with frontend dockerfile.v0: failed to create LLB definition: circular dependency detected on stage: dep`. You need to move `FROM composer:2 as dep` above `FROM scratch`, so with large `Dockerfile`, with multistage build, you would need to move these meta-targets above the rest and IMHO it would make this file harder to read.

In terms of layer optimisation I did some simple research and it looks like there's no difference in images' history:

```
$ docker image history copy-from
IMAGE          CREATED      CREATED BY                                   SIZE      COMMENT
95e1707ad108   9 days ago   COPY /usr/bin/composer composer # buildkit   2.36MB    buildkit.dockerfile.v0

$ docker image history copy-from-dep
IMAGE          CREATED      CREATED BY                                     SIZE      COMMENT
adf1ab2e5bc1   9 days ago   COPY /usr/bin/composer ./composer # buildkit   2.36MB    buildkit.dockerfile.v0
```

Somehoe Buildkit reused cache regardless of how `COPY` is used. But I am not 100% sure if it does not have an impact with more complex `Dockerfile`s. Anyway, I find `DL3022` rule confusing, to say least.

**Comment by rittneje** [comment]
@Wirone In your earliest post, you wrote this:

> Hadolint encourages to merge consecutive `RUN`s into one to make less layers and on the other hand enforces 2 layers instead of 1 just because it requires copying from _targets_ while `COPY` can work with _images_ too.

This is what I was responding to. It is inaccurate to say that it enforces two layers, as the image that is produced will still only have one.

If you feel it is bad because it makes the Dockerfile more confusing, that is a separate argument. Personally, I don't have a strong preference between the two. I do however think hadolint could be a bit smarter here. If the `--from` argument has a colon in it, then it should treat it as an image name not a stage name (and verify it against the trusted registries).

> Since hadolint cannot perform network requests, I don't think this is a case we are interested in supporting

@lorenzo  Hadolint doesn't perform network requests to lint your `FROM` instructions either, and is somehow able to deal with aliases there. Consequently, to make such an argument against an analogous `COPY` instruction is inconsistent, especially when the "workaround" is to use a `FROM` instruction.

**Comment by Wirone** [comment]
> > Hadolint encourages to merge consecutive `RUN`s into one to make less layers and on the other hand enforces 2 layers instead of 1 just because it requires copying from _targets_ while `COPY` can work with _images_ too.
> 
> This is what I was responding to. It is inaccurate to say that it enforces two layers, as the image that is produced will still only have one.

@rittneje Yeah, I agree 🙂 I should use other wording there. Hadolint enforces 2 instructions, which results in more intermediate containers, but maybe not necessarily 2 layers. 

> I do however think hadolint could be a bit smarter here. If the --from argument has a colon in it, then it should treat it as an image name not a stage name (and verify it against the trusted registries).

💯 👍 . Since `:` is not allowed in targets' names, it should be possible to distinguish `COPY` from targets and from images. There would be edge case when using `COPY --from=composer` without tag (using implicit `latest`) but probably it could encourage people for using explicit versions.

**Comment by Wirone** [comment]
@lorenzo I had never dealt with Haskell, I can probably look at it without any guarantee that I will deliver something meaningful 😉

**Comment by lorenzo** [comment]
@Wirone The fix should be trivial. Add a case above this one to check if the `s` variable contains a `:` https://github.com/hadolint/hadolint/blob/master/src/Hadolint/Rule/DL3022.hs#L16

Do that on the left side of the `=` sign and use the `st` result like in the line I referenced

**Comment by akostadinov** [comment]
Seems like this check is mostly useless. It is not checking for good style but for whether it works or not. If it works, then it is fine IMO so no need for linter to check it at all.
