### ISSUE TITLE
Recurse over directories

### ISSUE THREAD

**Issue by mcandre** [hadolint/hadolint#283]
- [ ] This is a bug report
- [x] This is a feature request
- [x] I searched existing issues before opening this one

As a developer, I want hadolint to automatically look for `Dockerfile*` paths within directory trees, so that I can quickly lint large Docker projects that may contain many Dockerfile's.

**Comment by zemanlx** [comment]
This is handled by your IDE plugin for hadolint to detect what is `Dockerfile` because some called they Dockefiles with a suffix some with a prefix, so it is hard to guess what is real Dockerfile.

I am using this in CI if that is your use case.

```bash
git ls-files --exclude='Dockerfile*' --ignored | xargs --max-lines=1 hadolint
```

This will ensure that you do not get `Dockerfiles` from `.git` or ignored files.

**Comment by richmidwinter** [comment]
find . -type f -name "Dockerfile*" -exec hadolint {} \;
