### ISSUE TITLE
Virus detected id in windows

### ISSUE THREAD

**Issue by Koma-Andrea** [hadolint/hadolint#402]
![image](https://user-images.githubusercontent.com/247170/75240653-fb53c880-57c4-11ea-9f5a-22a845236c35.png)

**Comment by lorenzo** [comment]
We produce the binaries from Travis, so it is very likely that this is a false positive.

You can choose to run hadolint using our official docker image, which should not suffer from this problem

**Comment by zemanlx** [comment]
Windows binary is actually built in Appveyor service, but it still means that your alert is with high chance false positive or it's got infected elsewhere. I have just checked our latest release with Virustotal and it looks clean.
https://www.virustotal.com/gui/url/887f1ee68c84b092f8dad3b7694debd57aab80c797eeda88c531c17b4bb6d811/detection

Please check that your file is not modified (they have same hash).

**Comment by verglor** [comment]
@lorenzo  @zemanlx I just downloaded v1.17.5 of [hadolint-Windows-x86_64.exe](https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Windows-x86_64.exe) from releases, but it has different checksum as the one cached in VirusTotal.

```
wget https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Windows-x86_64.exe
sha256sum hadolint-Windows-x86_64.exe 
35aa6f3e674582678d3a41a5d50d0fa4345dc378e8b3d6d202afe15a749cb379  hadolint-Windows-x86_64.exe
```

VirusTotal:
* by URL: [887f1ee68c84b092f8dad3b7694debd57aab80c797eeda88c531c17b4bb6d811](https://www.virustotal.com/gui/url/887f1ee68c84b092f8dad3b7694debd57aab80c797eeda88c531c17b4bb6d811/detection) 
* by upload: [35aa6f3e674582678d3a41a5d50d0fa4345dc378e8b3d6d202afe15a749cb379](https://www.virustotal.com/gui/file/35aa6f3e674582678d3a41a5d50d0fa4345dc378e8b3d6d202afe15a749cb379)

![](https://i.imgur.com/l1d5K4a.png)

So I think this issue should be reopened and investigated.

**Comment by zemanlx** [comment]
@verglor thank you for bringing this to our attention.

I have checked that binary has not been modified since its first upload by our [CI build](https://ci.appveyor.com/project/hadolint/hadolint/builds/30453174). If you run [API call](https://api.github.com/repos/hadolint/hadolint/releases/latest) to release v1.17.5 you get this for our Windows release:

```json
{
  "url": "https://api.github.com/repos/hadolint/hadolint/releases/assets/17675698",
  "id": 17675698,
  "node_id": "MDEyOlJlbGVhc2VBc3NldDE3Njc1Njk4",
  "name": "hadolint-Windows-x86_64.exe",
  "label": "",
  "uploader": {
    "login": "zemanlx",
    "id": 18702153,
    "node_id": "MDQ6VXNlcjE4NzAyMTUz",
    "avatar_url": "https://avatars1.githubusercontent.com/u/18702153?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/zemanlx",
    "html_url": "https://github.com/zemanlx",
    "followers_url": "https://api.github.com/users/zemanlx/followers",
    "following_url": "https://api.github.com/users/zemanlx/following{/other_user}",
    "gists_url": "https://api.github.com/users/zemanlx/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/zemanlx/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zemanlx/subscriptions",
    "organizations_url": "https://api.github.com/users/zemanlx/orgs",
    "repos_url": "https://api.github.com/users/zemanlx/repos",
    "events_url": "https://api.github.com/users/zemanlx/events{/privacy}",
    "received_events_url": "https://api.github.com/users/zemanlx/received_events",
    "type": "User",
    "site_admin": false
  },
  "content_type": "application/octet-stream",
  "state": "uploaded",
  "size": 4381696,
  "download_count": 325,
  "created_at": "2020-01-30T08:21:45Z",
  "updated_at": "2020-01-30T08:21:46Z",
  "browser_download_url": "https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Windows-x86_64.exe"
}
```
which matches time from CI run and it was uploaded using my token so no third party involvement in this.

I have played with VirusTotal and it behaves in an interesting way. Both of your links are pointing to the same file. If you look into details you can see that both links are pointing to the same SHA256 sum 
![image](https://user-images.githubusercontent.com/18702153/76142235-805f9d00-6063-11ea-9a68-78ebecb18562.png)

@verglor Do you have any windows computer to run tests there?

**Comment by verglor** [comment]
This is really strange - I have reported it to VirusTotal.
I have windows computer, but I don't know what tests do you mean.
I just tried to run it and windows defender has detected severe infection by trojan virus as reported by OP.

**Comment by zemanlx** [comment]
Thank you @verglor! I believe it is a false positive. I have reported it to Microsoft https://www.microsoft.com/en-us/wdsi/submission/acce378c-c64b-4adb-859a-d7d98990cb76.

I hope that they will have the same opinion as me and fix this for you guys. So far it looks good on a client.
![image](https://user-images.githubusercontent.com/18702153/76168340-fdc00600-6166-11ea-923b-8784baffd6cc.png)

**Comment by verglor** [comment]
This is reply from VirusTotal:

> This can happen when the URL from the download is safe in terms that it doesn't take malicious actions, but the downloaded file is malicious as when you open it then it will execute malicious code.
Imagine for example you create a safe website for uploading/downloading files and someone uploads a malicious file. When a user downloads this file from your site there is no problem as long as they don't open the file. That is because your site and the download url are safe but the file is not.

It means, that scaning URL in VirusTotal is actually useless and you always have to upload file for analysis. So the fact is that currently 16 engines consider this file as severe threat (and counting since 3 days ago it was 14):

![](https://i.imgur.com/XCCsDfY.png)

I suggest to reopen this issue and investigate why all these engines detect trojan virus. Submitting to Microsoft will not solve all other engines.

Since this application is just linter and not some system utility where false positive would be more understandable it is really suspicious.

**Comment by zemanlx** [comment]
That is really interesting way how to run the virus scan.

Microsoft has removed hadolint as a trojan malware :tada: and TBH I do not care that much about the other no-name antivirus software.

If you feel strongly about any of them feel free to report it as I have done it for Microsoft.

**Comment by lorenzo** [comment]
@verglor would you mind compiling `hadolint` locally, compress it with ` upx --best --ultra-brute` and then testing it for viruses?

That way we can see if the problem is appveyor
