### ISSUE TITLE
apk add $buildDeps returns SC2086, apk add "$buildDeps" breaks apk

### ISSUE THREAD

**Issue by aminvakil** [hadolint/hadolint#427]
- [x] This is a bug report
- [ ] This is a feature request
- [x] I searched existing issues before opening this one

```
RUN buildDeps=" \
		curl \
...
	"; \
	set -x \
	&& apk add --update --virtual .build-deps $buildDeps
```
Gives me `SC2086 Double quote to prevent globbing and word splitting.`

```
RUN buildDeps=" \
		curl \
...
	"; \
	set -x \
	&& apk add --update --virtual .build-deps
	"$buildDeps"
```
Breaks apk add with return code 99.
```
+ apk add --update --virtual .build-deps '
curl
...
'
ERROR: 'curl' is not a valid child dependency, format is name([<>~=]version)
```

Output of `hadolint --version`:
Haskell Dockerfile Linter v1.17.6-0-gc918759

**Dockerfile** (if relevant)
https://github.com/aminvakil/docker-ocserv/blob/master/Dockerfile
Line 26 & 48

I've temporarily ignored SC2086 to pass travis tests, but I really want to fix this in order to use this check as well.

I've just found this repo yesterday and I'm fixing issues on my Dockerfiles since then, it's great, thanks!

**Comment by zemanlx** [comment]
Hi @aminvakil, IMHO this is about shell features that you want to use in your Dockerfile. In this case, `buildDeps` has the purpose of an array, but it is not an array, but one string with spaces in it. This is useful if you are dealing with files with spaces in names that you need to loop through and so on. That's why `shellcheck` is complaining and when you fix complains it breaks your code. 

Let say that you need to pass two files to your program as arguments

```bash
#!/bin/bash

set -x

first="First file.txt"
second="I really love spaces.txt"

echo "first" > "$first"
echo "second" > "$second"
cat "$first" "$second"
```

and output will be 

```bash
+ first='First file.txt'
+ second='I really love spaces.txt'
+ echo first
+ echo second
+ cat 'First file.txt' 'I really love spaces.txt'
first
second
```

which is exactly what you need when you have variables with spaces. So `cat` is not trying to concatenate files `First` and `file.txt` and `I` and `really`, etc. but only two files `First file.txt` and `I really love spaces.txt`. 

In your case, you have a list which should be treated as a list of packages that you want to install and therefore you cannot quote it if you do not want it to be treated as one package with spaces in its name.

You have a few options:
1. Do nothing and ignore it via inline ignore. A dangerous path full of dragons and bugs later when you do not need them.
2. Do something hacky like this https://stackoverflow.com/questions/29295276/how-to-use-array-in-ash
3. Use arrays build for this purpose. Unfortunately, arrays are not supported in `ash` and you will need `bash` or some other shell that supports them. Then you can change your Dockerfile slightly to something like this

    ```Dockefile
    RUN buildDeps=( \
            curl \
            g++ \
        ); \
        set -x \
        && apk add --update --virtual .build-deps "${buildDeps[@]"
    ```

    which will expand you `apk` to

    ```bash
    apk add --update --virtual .build-deps "curl" "g++" 
    ```
4. Something else what is really elegant and it did not cross my mind.

Hope it helps! Please let us know as also others with a similar issue can find your solution useful.

**Comment by aminvakil** [comment]
As I don't think installing bash on this docker image is overkill, I used your number 3 approach which was building an array and passing it to apk.

There is a string in Dockerfile which it is generated by `scanelf`, `awk`, etc. and as I have little experience working with strings in bash, took my some time to fix it, I'm writing it for future readers although it's just about bash and has nothing to do with hadolint and of course it's not a bug.

I used `readarray` to split a string which its words are seperated via newline like this:

```
...
	&& runDeps="$( \
		scanelf --needed --nobanner /usr/local/sbin/ocserv \
			| awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
			| xargs -r apk info --installed \
			| sort -u \
		)" \
	&& readarray runDepsArr <<< "$runDeps" \
	&& apk add --virtual .run-deps "${runDepsArr[@]}" gnutls-utils iptables libnl3 readline \
...
```

For further read, you can read my commit, line 50:

https://github.com/aminvakil/docker-ocserv/commit/5b3c8efdde2d91dbf84bc11ee737793aa245d99a
