### ISSUE TITLE
feat: configuration via env variables

### ISSUE THREAD

**Issue by lukasmrtvy** [hadolint/hadolint#570]
- [ ] This is a bug report
- [X] This is a feature request
- [ ] I searched existing issues before opening this one

Would be nice to support configuration via ENV variables ( for example for --ignore `INGORE="DL3004,DL3005,DL3006"`), sometimes is not needed to create yaml config file ( mostly CI ), for dynamic configuration some templating must be done in hadonlint config file, then there is an alternative for suppressing rules from Dockerfile, last chance is creating some script for constructing dynamic arguments for hadolint, thats not easy in alpine image ( there is no bash )

**Comment by m-ildefons** [comment]
I like the idea, but this can be done with a bit of shell trickery already. Note that the alpine image has no bash, but it does have `/bin/sh` from BusyBox v1.32.1.
```bash
$ docker run --rm -i -e HADOLINT_OPTIONS="--ignore=DL3033" hadolint/hadolint:latest-alpine /bin/sh -c "/bin/hadolint \$HADOLINT_OPTIONS -" < Dockerfile
```
There also is a debian based image, which comes with dash iirc. Beware that this only works in the alpine or debian based images, because those are the only one with a shell.

Or if you are not using Docker, it is much simpler:
```bash
$ HADOLINT_OPTIONS="--ignore=DL3004"
$ hadolint $HADOLINT_OPTIONS Dockerfile
```

**Comment by lukasmrtvy** [comment]
@m-ildefons did You try to use multiple arguments ? `HADOLINT_OPTIONS="--ignore=DL3004 --ignore=DL3006"` this can not work. 

What is exact order of loading configuration ? 
1. arguments
2. hadolint config file 
3. dockerfile

? Thanks

**Comment by m-ildefons** [comment]
Be sure to use correct quoting for the shell, multiple arguments work just fine this way
In order to use the config file it must obviously be mounted into the container, but works fine too. The pragmas from the Dockerfile are respected as well:
```
$ docker run \
      --rm \
      -i \
      -e HADOLINT_OPTIONS="--ignore=DL3000 --ignore=DL3001" \
      -v /path/to/hadolint.yaml:/hadolint.yaml \
      hadolint/hadolint:latest-alpine \
        /bin/sh -c "/bin/hadolint -c /hadolint.yaml \$HADOLINT_OPTIONS -" < Dockerfile
```
I've broken this command up into multiple lines for readability.

Note, that for the label schema, the command line arguments *override* the config file. For others, including `--ignore`, the options are merged. This is because the label schema is a map and not a list, so merging would be very hard to get right.
Just like the commandline options, the pragmas in the Dockerfile are merged with the other options as well.

A config file of
```yaml
ignored:
  - DL3000
  - DL3001
```
together with commandline options `--ignore=DL3001 --ignore=DL3002` and a pragma in the Dockerfile of
```
# hadolint ignore=DL3002
# hadolint ignore=DL3003
```
will thus result in rules `DL3000`, `DL3001`, `DL0332` and `DL3003` to be ignored.
