### ISSUE TITLE
Rule suggestion: Recommend `ADD [some_url]` over `RUN wget [some_url]`

### ISSUE THREAD

**Issue by backus** [hadolint/hadolint#64]
I didn't realize that `ADD` supports URLs and, by moving my `RUN wget` usage to `ADD` instructions, I was able to drop `wget` as a dependency

**Comment by backus** [comment]
Same for `curl` of course

**Comment by lukasmartinelli** [comment]
> I didn't realize that ADD supports URLs and, by moving my RUN wget usage to ADD instructions, I was able to drop wget as a dependency

I am not sure about this. Docker thinks it is ok: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/


You should not add an archived file via `ADD` from a remote url because then it doesn't unpack it and you keep the artifact. For non archived file `ADD` might be still good replacement for wget?

So if we implement a rule like this it should only apply to **non-archives**.

<img width="701" alt="best_practices_for_writing_dockerfiles" src="https://cloud.githubusercontent.com/assets/1288339/18301535/8b4e8f80-74d2-11e6-9be1-076073e46ff2.png">

Discussion here: https://github.com/jwilder/nginx-proxy/issues/79

**Comment by ye** [comment]
I think this is covered in #55

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli I don't think ADD remote tarball file will leave any artifacts, all the untar / uncompress work is done in streaming fashion I believe.

I experienced something like that when downloading files with ADD and curl/wget.

`ADD` only supports archive when using it locally. `ADD lala.gz` will store the contents of `lala.gz`. When you download `ADD http://lala.gz` it will store the `lala.gz` and not the unpacked files.

**Comment by ye** [comment]
@lukasmartinelli ok you are right :)

**Comment by lorenzo** [comment]
I'm closing this as the suggestion is discouraged by the docker docs
