### ISSUE TITLE
executable validation?

### ISSUE THREAD

**Issue by abathur** [hadolint/hadolint#879]
@hadolint @lorenzo 

This isn't really an issue/request, but I couldn't find a more obvious way to reach out. Feel free to close here and reach out elsewhere if you prefer :)

I just stumbled on hadolint and wondered if ensuring that invoked executables are present is also a need here and if you see it as in scope?

I suspect it's out of scope for a linter, but if not I build https://github.com/abathur/resholve for identifying missing shell-script dependencies in Nix builds. (It's technically a generic/agnostic CLI tool, but it's only packaged for Nix since that's the immediate purpose.)

**Comment by m-ildefons** [comment]
Hey Travis,

this is an interesting idea and would be very helpful indeed, however Hadolint only has the source of the Dockerfile to work with and so far everything that requires introspecting the actual image built from that has been considered out of scope. That is also the reason, why environment variables aren't expanded before linting - we can't always know what value they would take without executing the image build. Keep in mind that sometimes the environment can also change by means of build-time arguments and `ARG` instructions. And containers can have volumes mounted at run time, which may also provide additional programs - in theory.
Also files and executables that aren't brought in during package installation or the build process itself might already be present in the base image. And then just because an executable is there, doesn't mean that it will work, because a shared library might be missing or have the wrong version or so. And that's before we're talking about _finding_ said executables and shared libraries, because an invocation may still fail if the executable isn't on the `$PATH`... I fear that if you dig down far enough this becomes the halting problem all over again.
So you see, determining if an image is actually missing something is very hard and alerting on that fact is even harder.

An analogous idea that might be possible would be to search the build context for missing files, but I currently can't say for sure if it would always be possible to determine for sure if a file is there. And it's totally possible that the build context is different from the directory the Dockerfile is located in.

Hope that answers your question.

Resholve looks very interesting, so thanks for bringing it to my attention.

**Comment by abathur** [comment]
> Hey Travis,
> 
> this is an interesting idea and would be very helpful indeed, however Hadolint only has the source of the Dockerfile to work with and so far everything that requires introspecting the actual image built from that has been considered out of scope... determining if an image is actually missing something is very hard and alerting on that fact is even harder.

Thanks for the context on how the problem(s) look from your perspective. I imagined that's where your scope boundary would be :)

resholve approaches sticky/tricky problems like these (no response or action expected--just sharing some detail in kind) by just blocking on anything it can't find and making the user disambiguate. For example, the _resholve way_ to handle a command that would only be present when some mount was available would be to block on its absence and make the user do something like:
- supply it at resolve time
- supply an absolute path for it
- tell resholve to ignore its absence

> Hope that answers your question.

Very much so--thanks for your time.
