### ISSUE TITLE
DL3013  -- pip versioning -- warning about local installation

### ISSUE THREAD

**Issue by Spindel** [hadolint/hadolint#88]
The stanza `pip install .` or `pip install '.[testing]'`  are done inside an unpacked source code to install all the dependencies / software via setup.py  (rather than doing `python setup.py install`)

When the argument to `pip install` is a directory (`.`)  it _is_ strictly versioned, as you may assume that we know who added the source into the container.

**Comment by zemanlx** [comment]
I did a bit of research in this and looks like that safe option should be `pip install --no-deps .` according to [pip docs](https://pip.pypa.io/en/stable/reference/pip_install/#hash-checking-mode) (see below). 
So I expect that in Docker, you would install dependencies from requirements file of by listing it in `pip install` and then by `pip install --no-deps .`. What do you think @Spindel?

---
Be careful not to nullify all your security work when you install your actual project by using setuptools directly: for example, by calling python `setup.py install`, `python setup.py develop`, or `easy_install`. Setuptools will happily go out and download, unchecked, anything you missed in your requirements file—and it’s easy to miss things as your project evolves. To be safe, install your project using pip and --no-deps.
Instead of `python setup.py develop`, use...
```bash
pip install --no-deps -e .
```
Instead of `python setup.py install`, use...
```bash
pip install --no-deps .
```

**Comment by mortenlj** [comment]
This is touching on an area where the python community is somewhat split.

In my opinion, `setup.py` needs to list all the dependencies of a project, because that's how many people will end up installing the package. When all dependencies are listed in `setup.py`, I don't want the added burden of making sure a duplicate list in `requirements.txt` is also updated.

If you don't need or want the extra features available in `requirements.txt`, there is little use for it, and the natural way to install the package when developing is `pip install -e .`, which will install the dependencies listed in `setup.py`, along with your package. In a `Dockerfile`, you might want to skip the `-e`, but otherwise it's the same. As @Spindel says, that should be all the version specification needed.

**Comment by zemanlx** [comment]
@mortenlj How do know that you have all dependencies in your `setup.py` to eliminate this?
> Setuptools will happily go out and download, unchecked, anything you missed in your requirements file — and it’s easy to miss things as your project evolves.
I know that some package managers (`npm` or `yarn` for node) offer _lock_ file where package manager lists all dependencies to avoid this.

**Comment by mortenlj** [comment]
Again, this is probably about varying approaches. I don't want to specify all my transitive dependencies, so if I have listed package A, which depends on package B, I won't specify package B. It will get pulled in when I install package A anyway.

If you are paranoid about making sure every installed package matches the hash it had when you installed it locally, then you probably want to list all transitive dependencies too. In that case, you have to use `requirements.txt` anyway. Personally, I put a bit of faith into the integrity of the package index instead (which I guess some people think is misguided :sweat_smile:).

**Comment by mortenlj** [comment]
> @mortenlj IMHO that is not only paranoid approach, but it is also against DL3013 to have a deterministic build.

I can still pin my versions in setup.py, and if all my dependencies also pin their versions, then there is no problem with deterministic builds.

> Anyway, I am not a python developer so if this is the reality of your world I am happy to add pip install . as an accepted option and move responsibility to a maintainer of setup.py file.

It would certainly be preferable for me. I can't speak for every python developer in the world though. :smile: 

> I am interested in the use case for pip install -e . in Dockerfile. Can you give me more insight on this one? I have thought that is only for development.

Thinking about it, I agree that in a Dockerfile, there probably isn't a good reason to use `-e`.
